version: 2.1
jobs:
  build:
    working_directory: ~/sunbird-pdf-player
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout:
          path: ~/sunbird-pdf-player
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
